apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa3-project
  namespace: argocd
spec:
  description: QA3 environment
  sourceRepos:
  - https://github.com/VETRI9876/argocd-rbac.git
  - https://github.com/argoproj/argocd-example-apps.git
  destinations:
  - namespace: qa3
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc  
  roles:
  - name: admin
    description: Admin access to QA3
    groups:
    - neuvector-admin
    policies:
    - p, proj:qa3-project:admin, applications, get, qa3-project/*, allow
    - p, proj:qa3-project:admin, applications, list, qa3-project/*, allow
    - p, proj:qa3-project:admin, applications, sync, qa3-project/*, allow
    - p, proj:qa3-project:admin, applications, update, qa3-project/*, allow
    - p, proj:qa3-project:admin, applications, delete, qa3-project/*, allow
    - p, proj:qa3-project:admin, applications, create, qa3-project/*, allow


  - name: readonly
    description: Read-only access to QA3
    groups:
    - ARGO-CD-TestGroup-Iskan
    policies:
    - p, proj:qa3-project:readonly, applications, get, qa3-project/*, allow
    - p, proj:qa3-project:readonly, applications, list, qa3-project/*, allow
