apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa3-project
  namespace: argocd
spec:
  description: QA3 environment
  sourceRepos:
  - https://github.com/VETRI9876/argocd-rbac.git
  destinations:
  - namespace: qa3
    server: https://kubernetes.default.svc
  roles:
  - name: admin
    description: Admin access to QA3
    groups:
    - e80ad58d-c54d-4082-8cf0-157e2120d081
    policies:
    - p, proj:qa3-project:admin, applications, *, qa3-project/*, allow

  - name: readonly
    description: Read-only access to QA3
    groups:
    - ca320113-f856-4e4c-bdc9-0bf23d828854
    policies:
    - p, proj:qa3-project:readonly, applications, get, qa3-project/*, allow
    - p, proj:qa3-project:readonly, applications, list, qa3-project/*, allow
