apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa5-project
  namespace: argocd
spec:
  description: QA5 environment
  sourceRepos:
  - https://github.com/VETRI9876/argocd-rbac.git
  - https://github.com/argoproj/argocd-example-apps.git
  destinations:
  - namespace: qa5
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  roles:
  - name: admin
    description: Admin access to QA5
    groups:
    - neuvector-admin
    policies:
    - p, proj:qa5-project:admin, applications, *, qa5-project/*, allow

  - name: readonly
    description: Read-only access to QA5
    groups:
    - ARGO-CD-TestGroup-Iskan
    policies:
    - p, proj:qa5-project:readonly, applications, get, qa5-project/*, allow
    - p, proj:qa5-project:readonly, applications, list, qa5-project/*, allow
