apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa5-project
  namespace: argocd
spec:
  description: QA5 environment
  sourceRepos:
    - https://github.com/VETRI9876/argocd-rbac.git
    - https://github.com/argoproj/argocd-example-apps.git

  destinations:
    - namespace: qa5
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  roles:
    - name: admin
      description: Admin access to QA5
      groups:
        - ca320113-f856-4e4c-bdc9-0bf23d828854 # ARGO-CD-TestGroup-Iskan
      policies:
        - p, proj:qa5-project:admin, applications, get, qa5-project/*, allow
        - p, proj:qa5-project:admin, applications, list, qa5-project/*, allow
        - p, proj:qa5-project:admin, applications, sync, qa5-project/*, allow
        - p, proj:qa5-project:admin, applications, update, qa5-project/*, allow
        - p, proj:qa5-project:admin, applications, delete, qa5-project/*, allow
        - p, proj:qa5-project:admin, applications, create, qa5-project/*, allow

    - name: readonly
      description: Read-only access to QA5
      groups:
        - e80ad58d-c54d-4082-8cf0-157e2120d081 # neuvector-admin
      policies:
        - p, proj:qa5-project:readonly, applications, get, qa5-project/*, allow
        - p, proj:qa5-project:readonly, applications, list, qa5-project/*, allow

    - name: restricted-admin
      description: Restricted Admin (sync/update only)
      groups:
        - e17ea958-23ad-4152-8506-473b8ce6fe3a # ADF-FDF-POC-TEST (Restricted Admin)
      policies:
        - p, proj:qa5-project:restricted-admin, applications, get, qa5-project/*, allow
        - p, proj:qa5-project:restricted-admin, applications, list, qa5-project/*, allow
        - p, proj:qa5-project:restricted-admin, applications, sync, qa5-project/*, allow
        - p, proj:qa5-project:restricted-admin, applications, update, qa5-project/*, allow
