apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:org-readonly

  policy.csv: |
    #################################################
    # ORG READ-ONLY ROLE (EXPLICIT)
    #################################################
    p, role:org-readonly, applications, get, */*, allow
    p, role:org-readonly, applications, list, */*, allow
    p, role:org-readonly, applicationsets, get, */*, allow
    p, role:org-readonly, projects, get, *, allow
    p, role:org-readonly, clusters, get, *, allow
    p, role:org-readonly, repositories, get, *, allow
    p, role:org-readonly, accounts, get, *, allow
    p, role:org-readonly, logs, get, */*, allow

    #################################################
    # ORG ADMIN ROLE (qa3, qa4, qa5 ONLY)
    #################################################
    p, role:org-admin, applications, *, qa-admin-project/*, allow
    p, role:org-admin, applicationsets, *, qa-admin-project/*, allow
    p, role:org-admin, projects, get, qa-admin-project, allow
    p, role:org-admin, logs, get, qa-admin-project/*, allow

    #################################################
    # GROUP ROLE MAPPING
    #################################################
    g, e80ad58d-c54d-4082-8cf0-157e2120d081, role:org-readonly
    g, ca320113-f856-4e4c-bdc9-0bf23d828854, role:org-admin
