apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa-admin-project
  namespace: argocd
spec:
  description: QA admin access limited to qa3, qa4, qa5 only
  sourceRepos:
    - https://github.com/VETRI9876/argocd-rbac.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: qa3
    - server: https://kubernetes.default.svc
      namespace: qa4
    - server: https://kubernetes.default.svc
      namespace: qa5
  namespaceResourceWhitelist:
    - group: '*'  # Allow to manage ALL resource types inside namespaces
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'  # Allow to manage ALL cluster-level resources
      kind: '*'
  orphanedResources:
    warn: true
